# Generated by Django 5.0.6 on 2024-07-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="avatar",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="userdetail",
            name="social_contact",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
