# Generated by Django 5.0.6 on 2024-07-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_userdetail_avatar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userdetail",
            name="hobby",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
