# Generated by Django 5.0.6 on 2024-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FriendLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="网站名字")),
                ("intro", models.CharField(max_length=120, verbose_name="网站简介")),
                ("link", models.URLField(verbose_name="网站链接")),
                ("avatar", models.URLField(verbose_name="网站头像")),
                (
                    "email",
                    models.EmailField(max_length=254, unique=True, verbose_name="邮箱"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "审核"),
                            ("on_shelf", "上架"),
                            ("off_shelf", "下架"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="链接状态",
                    ),
                ),
            ],
            options={
                "db_table": "friendlink",
            },
        ),
        migrations.CreateModel(
            name="FriendLinkStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField()),
            ],
            options={
                "db_table": "fl_statement",
            },
        ),
    ]
