# Generated by Django 5.0.6 on 2024-08-26 01:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("friendlink", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="friendlink",
            table="friendlink",
        ),
    ]
