# Generated by Django 5.0.6 on 2024-08-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("friendlink", "0002_alter_friendlink_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="FriendLinkStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("statement", models.TextField()),
            ],
        ),
    ]
