# Generated by Django 5.0.6 on 2024-08-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogmeta",
            name="cover_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
