# Generated by Django 5.0.6 on 2024-08-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0002_blogmeta_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogmeta",
            name="cover",
            field=models.ImageField(upload_to="cover/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="blogmeta",
            name="title",
            field=models.CharField(max_length=25),
        ),
    ]
