# Generated by Django 5.0.6 on 2024-08-15 10:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meta", "0003_alter_blogmeta_cover_alter_blogmeta_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogmeta",
            name="cover_url",
        ),
    ]
