# Generated by Django 5.0.6 on 2024-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("color", models.CharField(default="#409eff", max_length=8)),
            ],
            options={
                "db_table": "tags",
            },
        ),
    ]
