# Generated by Django 5.0.6 on 2024-09-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="color",
            field=models.CharField(default="#409eff", max_length=8),
        ),
    ]
