# Generated by Django 5.0.6 on 2024-08-29 06:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("siteinfo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="siteinfo",
            table="site_info",
        ),
    ]
