# Generated by Django 5.0.6 on 2024-10-15 03:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="createTime",
            new_name="create_time",
        ),
        migrations.AlterModelTable(
            name="comments",
            table="comments",
        ),
    ]
