# Generated by Django 5.0.6 on 2024-10-15 03:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0002_rename_createtime_comments_create_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="article_id",
            new_name="article_pk",
        ),
    ]
