# Generated by Django 5.0.6 on 2024-10-15 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0003_rename_article_id_comments_article_pk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="parent_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="comments.comments",
                verbose_name="评论",
            ),
        ),
    ]
