# Generated by Django 5.0.6 on 2024-10-16 03:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0004_alter_comments_parent_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="notification",
            field=models.BooleanField(default=True, verbose_name="是否通知"),
        ),
    ]
