# Generated by Django 5.0.6 on 2024-10-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0005_comments_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="email",
            field=models.EmailField(
                default="2403428097@qq.com", max_length=254, verbose_name="用户接收回复的邮箱"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="comments",
            name="notification",
            field=models.BooleanField(default=True, verbose_name="是否接收回复通知"),
        ),
    ]
