# Generated by Django 5.0.6 on 2024-10-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0006_comments_email_alter_comments_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comments",
            name="content",
            field=models.TextField(max_length=255, verbose_name="评论内容"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="nickname",
            field=models.CharField(max_length=30, verbose_name="昵称"),
        ),
    ]
