# Generated by Django 5.0.6 on 2024-09-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PhotoWall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="photowall/%Y/%m/%d", verbose_name="图片"
                    ),
                ),
                ("description", models.CharField(max_length=255, verbose_name="图片介绍")),
                ("visible", models.BooleanField(default=True, verbose_name="是否可见")),
            ],
            options={
                "db_table": "photowall",
            },
        ),
    ]
