# Generated by Django 5.0.6 on 2024-08-29 03:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("photowall", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photowall",
            name="description",
            field=models.CharField(max_length=255, verbose_name="图片介绍"),
        ),
        migrations.AlterField(
            model_name="photowall",
            name="image",
            field=models.ImageField(upload_to="photowall/%Y/%m/%d", verbose_name="图片"),
        ),
        migrations.AlterField(
            model_name="photowall",
            name="visible",
            field=models.BooleanField(default=True, verbose_name="是否可见"),
        ),
    ]
