# Generated by Django 5.0.6 on 2024-09-21 14:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "photowall",
            "0002_alter_photowall_description_alter_photowall_image_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTable(
            name="photowall",
            table="photowall",
        ),
    ]
