# Generated by Django 5.0.6 on 2024-08-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display",
            field=models.BooleanField(default=False, verbose_name="是否展示到主页"),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=10, verbose_name="分类名"),
        ),
    ]
