# Generated by Django 5.0.6 on 2024-09-29 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdminLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="setting/logo/%Y/%m/%d", verbose_name="后台LOGO"
                    ),
                ),
            ],
            options={
                "db_table": "admin_logo",
            },
        ),
        migrations.CreateModel(
            name="FrontCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="setting/cover/%Y/%m/%d", verbose_name="前台封面"
                    ),
                ),
            ],
            options={
                "db_table": "front_cover",
            },
        ),
        migrations.CreateModel(
            name="SettingsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="分组名")),
                (
                    "owner",
                    models.IntegerField(default=-1, null=True, verbose_name="从属分组ID"),
                ),
            ],
            options={
                "db_table": "settings_group",
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(blank=True, max_length=255)),
                ("value", models.CharField(max_length=255)),
                (
                    "groupId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="settings.settingsgroup",
                    ),
                ),
            ],
            options={
                "db_table": "settings",
            },
        ),
    ]
