# Generated by Django 5.0.6 on 2024-08-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0002_settingsgroup_settings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settingsgroup",
            name="owner",
            field=models.IntegerField(default=-1, null=True, verbose_name="从属分组ID"),
        ),
    ]
