# Generated by Django 5.0.6 on 2024-09-03 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0003_alter_settingsgroup_owner"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BlogSettings",
        ),
    ]
