# Generated by Django 5.0.6 on 2024-09-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0004_delete_blogsettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        upload_to="setting/logo/%Y/%m/%d", verbose_name="后台LOGO"
                    ),
                ),
            ],
            options={
                "db_table": "admin_logo",
            },
        ),
        migrations.CreateModel(
            name="FrontCover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        upload_to="setting/cover/%Y/%m/%d", verbose_name="前台封面"
                    ),
                ),
            ],
            options={
                "db_table": "front_cover",
            },
        ),
    ]
