# Generated by Django 5.0.6 on 2024-09-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("settings", "0005_adminlogo_frontcover"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="key",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
