# Generated by Django 5.0.6 on 2024-06-13 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnualSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("create_year", models.IntegerField()),
                ("sum_up", models.TextField()),
                ("statistics_data", models.JSONField()),
            ],
            options={
                "db_table": "annual_summary",
            },
        ),
    ]
