# Generated by Django 5.0.6 on 2024-07-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annual_summary", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annualsummary",
            name="create_year",
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="annualsummary",
            name="sum_up",
            field=models.TextField(default="今年没有总结哦"),
        ),
    ]
