# Generated by Django 5.0.6 on 2024-10-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_url",
            field=models.CharField(max_length=400),
        ),
    ]
