# Generated by Django 5.0.6 on 2024-08-19 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="is_recommend",
            new_name="recommend",
        ),
        migrations.AddField(
            model_name="article",
            name="visible",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover",
            field=models.ImageField(upload_to="article/cover/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="article",
            name="intro",
            field=models.TextField(max_length=200),
        ),
    ]
