# Generated by Django 5.0.6 on 2024-08-23 02:48

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_rename_is_recommend_article_recommend_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=article.models.ImageContent.upload_to_with_uuid
                    ),
                ),
            ],
        ),
    ]
