# Generated by Django 5.0.6 on 2024-10-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0002_alter_article_cover_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_url",
            field=models.URLField(),
        ),
    ]
