# Generated by Django 5.0.6 on 2024-08-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0003_imagecontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cover",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(upload_to="article/cover/%Y/%m/%d")),
            ],
        ),
        migrations.RemoveField(
            model_name="article",
            name="cover",
        ),
        migrations.AddField(
            model_name="article",
            name="cover_url",
            field=models.URLField(default=""),
            preserve_default=False,
        ),
    ]
